spring:
  application:
    name: msvc-paciente
  config:
    import: optional:configserver:http://localhost:8888


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka